# -*- coding: utf-8 -*-
"""movie_rating_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZK6nZcrUonQqIjv7HEbOshoCxmmCFlyH

**Movie Rating System **
"""

import sqlite3
from tabulate import tabulate
from datetime import datetime

# Connect to SQLite Database
conn = sqlite3.connect('movies.db')
cursor = conn.cursor()

# =========================
# CREATE TABLE Operations
# =========================
cursor.execute('''
CREATE TABLE IF NOT EXISTS Movies (
    Movie_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Title TEXT NOT NULL,
    Director TEXT,
    Genre TEXT,
    Release_Year INTEGER
)
''')   # <-- CREATE TABLE: Movies

cursor.execute('''
CREATE TABLE IF NOT EXISTS Users (
    User_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    Contact TEXT
)
''')   # <-- CREATE TABLE: Users

cursor.execute('''
CREATE TABLE IF NOT EXISTS Ratings (
    Rating_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    User_ID INTEGER,
    Movie_ID INTEGER,
    Rating INTEGER CHECK(Rating >= 1 AND Rating <= 5),
    Review TEXT,
    Rating_Date TEXT,
    FOREIGN KEY (User_ID) REFERENCES Users(User_ID),
    FOREIGN KEY (Movie_ID) REFERENCES Movies(Movie_ID)
)
''')   # <-- CREATE TABLE: Ratings

conn.commit()

# =========================
# Functions for Operations
# =========================

def add_movie():
    title = input("Enter movie title: ")
    director = input("Enter director name: ")
    genre = input("Enter genre: ")
    year = int(input("Enter release year: "))

    # INSERT Operation
    cursor.execute("INSERT INTO Movies (Title, Director, Genre, Release_Year) VALUES (?, ?, ?, ?)",
                   (title, director, genre, year))   # <-- INSERT: Add movie
    conn.commit()
    print(f"Movie '{title}' added successfully.\n")

def view_movies():
    # SELECT Operation
    cursor.execute("SELECT * FROM Movies")   # <-- SELECT: View movies
    movies = cursor.fetchall()
    print(tabulate(movies, headers=["Movie ID", "Title", "Director", "Genre", "Release Year"], tablefmt="grid"))

def delete_movie():
    movie_id = int(input("Enter the Movie ID to delete: "))
    # DELETE Operation
    cursor.execute("DELETE FROM Movies WHERE Movie_ID = ?", (movie_id,))   # <-- DELETE: Remove movie
    conn.commit()
    print(f"Movie ID {movie_id} deleted successfully.\n")

def add_user():
    name = input("Enter user name: ")
    contact = input("Enter contact information: ")

    # INSERT Operation
    cursor.execute("INSERT INTO Users (Name, Contact) VALUES (?, ?)", (name, contact))   # <-- INSERT: Add user
    conn.commit()
    print(f"User '{name}' added successfully.\n")

def rate_movie():
    user_id = int(input("Enter User ID: "))
    movie_id = int(input("Enter Movie ID: "))
    rating = int(input("Enter rating (1-5): "))
    review = input("Enter review: ")
    rating_date = datetime.now().strftime("%Y-%m-%d")

    # INSERT Operation
    cursor.execute("INSERT INTO Ratings (User_ID, Movie_ID, Rating, Review, Rating_Date) VALUES (?, ?, ?, ?, ?)",
                   (user_id, movie_id, rating, review, rating_date))   # <-- INSERT: Add rating
    conn.commit()
    print(f"Movie ID {movie_id} rated successfully.\n")

def view_ratings():
    # SELECT with JOIN Operation
    cursor.execute('''
        SELECT r.Rating_ID, m.Title, u.Name, r.Rating, r.Review, r.Rating_Date
        FROM Ratings r
        JOIN Movies m ON r.Movie_ID = m.Movie_ID
        JOIN Users u ON r.User_ID = u.User_ID
    ''')   # <-- SELECT: View ratings with JOIN
    ratings = cursor.fetchall()
    print(tabulate(ratings, headers=["Rating ID", "Movie Title", "User", "Rating", "Review", "Date"], tablefmt="grid"))

def update_rating():
    rating_id = int(input("Enter Rating ID to update: "))
    new_rating = int(input("Enter new rating (1-5): "))
    new_review = input("Enter new review: ")

    # UPDATE Operation
    cursor.execute("UPDATE Ratings SET Rating = ?, Review = ? WHERE Rating_ID = ?",
                   (new_rating, new_review, rating_id))   # <-- UPDATE: Modify rating/review
    conn.commit()
    print(f"Rating ID {rating_id} updated successfully.\n")

def delete_rating():
    rating_id = int(input("Enter Rating ID to delete: "))
    # DELETE Operation
    cursor.execute("DELETE FROM Ratings WHERE Rating_ID = ?", (rating_id,))   # <-- DELETE: Remove rating
    conn.commit()
    print(f"Rating ID {rating_id} deleted successfully.\n")

# ===================
# Main Menu Function
# ===================

def menu():
    while True:
        print("\n=== Movie Rating System ===")
        print("1. Add Movie")
        print("2. View Movies")
        print("3. Delete Movie")
        print("4. Add User")
        print("5. Rate Movie")
        print("6. View Ratings")
        print("7. Update Rating")
        print("8. Delete Rating")
        print("9. Exit")

        choice = input("Enter your choice: ")

        if choice == '1':
            add_movie()
        elif choice == '2':
            view_movies()
        elif choice == '3':
            delete_movie()
        elif choice == '4':
            add_user()
        elif choice == '5':
            rate_movie()
        elif choice == '6':
            view_ratings()
        elif choice == '7':
            update_rating()
        elif choice == '8':
            delete_rating()
        elif choice == '9':
            print("Exiting the system.")
            break
        else:
            print("Invalid choice. Please try again.")

# Run the menu
menu()

# Close the connection
conn.close()

